---
title             : "PSY 8960-003 Reproducibility Project: Examining the Association Between Neuroticism and Loneliness Among College Students"
shorttitle        : "Reproducibility Project"

author: 
  - name          : "Caroline Armstrong"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "75 East River Parkway, Minneapolis, MN 55455"
    email         : "carolinearmstrong19@gmail.com"
    role: # Contributorship roles (e.g., CRediT, https://credit.niso.org/)
      - "Conceptualization"
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"

affiliation:
  - id            : "1"
    institution   : "Department of Psychology, University of Minnesota"

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  One or two sentences to put the results into a more **general context**.
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : "r-references.bib"

floatsintext      : no
linenumbers       : no
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
# Load libraries and set up such that packages used get cited
library(apaTables)
library(dplyr)
library(ggplot2)
library(gtsummary)
library("papaja")
library(psych)
r_refs("r-references.bib") # setting up such that packages used get cited
```

```{r analysis-preferences}
# Setting seed for reproducible results (seed for random number generation)
set.seed(121)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

```{r read-in-data}
# Read in simulated data (make sure you have downloaded full ZIP from GitHub and opened R project to avoid file path issues when reading in this data)
data_simulated <- read.csv("../data/neuroticism-loneliness_data-simulated_2025-12-01.csv")
```

[Intro - TO COME]

# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
